services:
  postgres:
    image: postgres:16
    container_name: jobtracker_postgres
    restart: always
    environment:
      POSTGRES_USER: jobtracker_user
      POSTGRES_PASSWORD: jobtracker_pass
      POSTGRES_DB: jobtracker_ai
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: